micronaut:
  application:
    name: micronautDemo
datasources:
  default:
    dialect: H2
    url: jdbc:h2:mem:personService;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format-sql: true